name: guru_cli
description: Master Command Line Interface for setting up Flutter project.
version: 0.0.1


environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  args: ^2.1.0
  glob: ^2.0.2
  lcov_parser: ^0.1.2
  mason: ">=0.1.0-dev.17 <0.1.0-dev.18"
  mason_logger: ^0.1.0-dev.8
  meta: ^1.3.0
  path: ^1.8.0
  pub_updater: ^0.2.1
  universal_io: ^2.0.4
  usage: ^4.0.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  build_version: ^2.0.0
  mocktail: ^0.2.0
  test: ^1.17.0